
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.Point;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.System.console;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import javax.swing.border.AbstractBorder;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jordenir
 */
public class AnalizarLexico extends javax.swing.JFrame {

    public String EnderecoArquivo,EnderecoTemporario,bufferIn;
        public String data ;
        public int resultadoJanelas;
    private Color myColor;
    
    /**
     * Creates new form AnalizarLexico
     */
       
    public AnalizarLexico() {
        initComponents();
        setLocationRelativeTo(null);
        jTextArea1.setBorder(new NumeredBorder());
       MostrarAtualizarDataHora();
       //Iniciamos um timer para atualizar o relÃ³gio  
        Timer t = new Timer("ClockTimer", true);  
          
        //Pedimos para ele disparar a cada 1 segundo.  
        t.schedule(new ClockTask(), 0, 1000);
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        Botao_Analizar_lexico = new javax.swing.JToggleButton();
        Botao_analizar_sintax = new javax.swing.JToggleButton();
        Botao_Abrir_Arquivo = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenssagemTxt = new java.awt.Label();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        botao1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton2.setText("Limpar saida");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton3.setText("Limpar Entrada");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton4.setText("Limpar tudo");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton1.setText("Atualizar Saida");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        Botao_Analizar_lexico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Botao_Analizar_lexico.setText("Analizar Lex");
        Botao_Analizar_lexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Analizar_lexicoActionPerformed(evt);
            }
        });

        Botao_analizar_sintax.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Botao_analizar_sintax.setText("Analizar Sintax");
        Botao_analizar_sintax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_analizar_sintaxActionPerformed(evt);
            }
        });

        Botao_Abrir_Arquivo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Botao_Abrir_Arquivo.setText("Abrir Arquivo");
        Botao_Abrir_Arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_Abrir_ArquivoActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrada de dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 36), new java.awt.Color(255, 0, 0))); // NOI18N
        jTextArea1.setCaretColor(new java.awt.Color(51, 0, 255));
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SaÃ­da de dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(51, 0, 204))); // NOI18N
        jTextArea2.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Entrada de dados");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Saida de dados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(297, 297, 297))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        MenssagemTxt.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        MenssagemTxt.setText("SaÃ­da de Menssagem");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Debugar SintÃ¡x");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton2.setText("Debugar Lookahead");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botao1.setText("jButton2");

        jMenu1.setText("Arquivo");

        jMenuItem2.setText("Abrir Arquivo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Analizar");

        jMenuItem1.setText("Analisar SintÃ¡tico");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem5.setText("Analisar Somente lÃ©xico");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Mostrar");

        jMenuItem4.setText("Listar Lexico");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Botao_Analizar_lexico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Botao_Abrir_Arquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Botao_analizar_sintax, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MenssagemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Botao_Abrir_Arquivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Botao_Analizar_lexico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Botao_analizar_sintax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenssagemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
        Analise();
        } catch (IOException ex) {
        Logger.getLogger(AnalizarLexico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AnalizarLexico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseEOFException ex) {
            Logger.getLogger(AnalizarLexico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser openFile = new JFileChooser();
                openFile.showOpenDialog(openFile);
                resultadoJanelas = JFileChooser.OPEN_DIALOG;
                
                if(JFileChooser.APPROVE_OPTION == resultadoJanelas){
                          EnderecoArquivo = openFile.getSelectedFile().toString();
                          AbrirArquivo();
                }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
       
       jTextArea2.setText("");
       jTextArea1.requestFocus();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        jTextArea1.setText("");
        jTextArea1.requestFocus();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextArea1.requestFocus();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       try {
        AnaliseLexSomente();
        } catch (IOException ex) {
        Logger.getLogger(AnalizarLexico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       jTextArea2.setText("");
       jTextArea1.requestFocus();
       
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void Botao_Analizar_lexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Analizar_lexicoActionPerformed
        
        try {
          scanner_1TokenManager.countLexError =0;
          MenssagemTxt.setText("");
          jTextArea2.setText("");
        AnaliseLexSomente();
        
       //MostrarNoPainel();
        } catch (IOException ex) {
        Logger.getLogger(AnalizarLexico.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea1.requestFocus();
    }//GEN-LAST:event_Botao_Analizar_lexicoActionPerformed

    private void Botao_analizar_sintaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_analizar_sintaxActionPerformed
              
        try {
            MenssagemTxt.setText("");
            //Painel1.clear();
            parser.contParseError = 0;
            scanner_1TokenManager.countLexError = 0;
            jTextArea2.setText("");
        Analise();
        if(parser.contParseError > 0 || scanner_1TokenManager.countLexError > 0){
    
    if(parser.contParseError > 0){
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    System.out.println(parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    
    }
    if(scanner_1TokenManager.countLexError > 0){
        System.out.println(scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    
    }
    MenssagemTxt.setText("Analize contÃ©m "+parser.contParseError+ " Erro(s) SintÃ¡tico"+ " e "+ scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico");
    MenssagemTxt.setBackground(Color.red);
    MenssagemTxt.setForeground(Color.WHITE);
    
}else{
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+"<<<<<<<<<< FINALIZADO COM SUCESSO. >>>>>>>>>>"+"\u005cn"+"\u005cn");
    MenssagemTxt.setText("Analize sem erro sintÃ¡tico");
    MenssagemTxt.setBackground(Color.GREEN);
    
}
        
       //MostrarNoPainel();
        } catch (IOException ex) {
        Logger.getLogger(AnalizarLexico.class.getName()).log(Level.SEVERE, null, ex);
        jTextArea2.setText(jTextArea2.getText()+"\u005cn\u005cn"+ex);
        if(parser.contParseError > 0 || scanner_1TokenManager.countLexError > 0){
    
    if(parser.contParseError > 0){
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    System.out.println(parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    
    }
    if(scanner_1TokenManager.countLexError > 0){
        System.out.println(scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    
    }
    MenssagemTxt.setText("Analize contÃ©m "+parser.contParseError+ " Erro(s) SintÃ¡tico"+ " e "+ scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico");
    MenssagemTxt.setBackground(Color.red);
    MenssagemTxt.setForeground(Color.WHITE);
    
}else{
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+"<<<<<<<<<< FINALIZADO COM SUCESSO. >>>>>>>>>>"+"\u005cn"+"\u005cn");
    MenssagemTxt.setText("Analize sem erro sintÃ¡tico");
    MenssagemTxt.setBackground(Color.GREEN);
    
}
        } catch (ParseException ex) {
            Logger.getLogger(AnalizarLexico.class.getName()).log(Level.SEVERE, null, ex);
            jTextArea2.setText(jTextArea2.getText()+"\u005cn\u005cn"+ex);
            parser.contParseError++;
            if(parser.contParseError > 0 || scanner_1TokenManager.countLexError > 0){
    
    if(parser.contParseError > 0){
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    System.out.println(parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    
    }
    if(scanner_1TokenManager.countLexError > 0){
        System.out.println(scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    
    }
    MenssagemTxt.setText("Analize contÃ©m "+parser.contParseError+ " Erro(s) SintÃ¡tico"+ " e "+ scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico");
    MenssagemTxt.setBackground(Color.red);
    MenssagemTxt.setForeground(Color.WHITE);
    
}else{
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+"<<<<<<<<<< FINALIZADO COM SUCESSO. >>>>>>>>>>"+"\u005cn"+"\u005cn");
    MenssagemTxt.setText("Analize sem erro sintÃ¡tico");
    MenssagemTxt.setBackground(Color.GREEN);
    
}
        } catch (ParseEOFException ex) {
            Logger.getLogger(AnalizarLexico.class.getName()).log(Level.SEVERE, null, ex);
            jTextArea2.setText(jTextArea2.getText()+"\u005cn\u005cn"+ex);
            if(parser.contParseError > 0 || scanner_1TokenManager.countLexError > 0){
    
    if(parser.contParseError > 0){
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    System.out.println(parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    
    }
    if(scanner_1TokenManager.countLexError > 0){
        System.out.println(scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    
    }
    MenssagemTxt.setText("Analize contÃ©m "+parser.contParseError+ " Erro(s) SintÃ¡tico"+ " e "+ scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico");
    MenssagemTxt.setBackground(Color.red);
    MenssagemTxt.setForeground(Color.WHITE);
    
}else{
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+"<<<<<<<<<< FINALIZADO COM SUCESSO. >>>>>>>>>>"+"\u005cn"+"\u005cn");
    MenssagemTxt.setText("Analize sem erro sintÃ¡tico");
    MenssagemTxt.setBackground(Color.GREEN);
    
}
        }
        jTextArea1.requestFocus();
    }//GEN-LAST:event_Botao_analizar_sintaxActionPerformed

    private void Botao_Abrir_ArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_Abrir_ArquivoActionPerformed
        JFileChooser openFile = new JFileChooser();
                openFile.showOpenDialog(openFile);
                resultadoJanelas = JFileChooser.OPEN_DIALOG;
                
                if(JFileChooser.APPROVE_OPTION == resultadoJanelas){
                          EnderecoArquivo = openFile.getSelectedFile().toString();
                          AbrirArquivo();
                }
                jTextArea1.requestFocus();
    }//GEN-LAST:event_Botao_Abrir_ArquivoActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()){
            JOptionPane.showMessageDialog(null,"VocÃª Ativou o debug-Sintax");
            scanner.debug_recovery = true;
        }
        else{
            JOptionPane.showMessageDialog(null,"VocÃª desativou o debug-Sintax");
            scanner.debug_recovery = false;
        }
	
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected()){
            JOptionPane.showMessageDialog(null,"VocÃª Ativou Debug-Lookahead");
            scanner.trace_enabled1 = true;
        }
        else{
            JOptionPane.showMessageDialog(null,"VocÃª desativou Debug-Lookahead");
            scanner.trace_enabled1 = false;
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea2.setText(jTextArea2.getText()+"\nManaus");
    }//GEN-LAST:event_jButton1ActionPerformed
int Nlinha;
    private void AbrirArquivo(){
                 try{
                          FileReader fileReader = new FileReader(EnderecoArquivo);
                          BufferedReader reader = new BufferedReader(fileReader);
                          while((data = reader.readLine()) != null){
                                 jTextArea1.append(data+"\n");
                                 Nlinha++;
                                 System.out.println("Linhas: "+ Nlinha);
                         }
                         fileReader.close();
                         reader.close();
                 }
                 catch(Exception erro){
                         JOptionPane.showMessageDialog(null, erro.getMessage());
                 }
         }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizarLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizarLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizarLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizarLexico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalizarLexico().setVisible(true);
                
            }
        });
    }




    Scanner_1 scanner;
    Scanner_1 parser;
    int i;
    boolean ms = false;
    boolean debug = false;
    Scanner_1 scanner1;
    private void Analise() throws IOException, ParseException, ParseEOFException{
                
                        EnderecoTemporario =  System.getProperty("java.io.tmpdir")+"temp.txt";
                 File arquivo = new File(EnderecoTemporario);  
                 FileWriter fw = new FileWriter(arquivo);  
                 BufferedWriter bw = new BufferedWriter(fw);      
                 bw.write(jTextArea1.getText());  
                 bw.flush();  
                 bw.close(); 
                              
                 String nomeArq = new String (EnderecoTemporario);
Scanner_1 lex = new Scanner_1(new FileInputStream(nomeArq));

String args[] = null;

if(jTextArea1.getText().equals("")){
    JOptionPane.showMessageDialog(null, "NÃ£o ha tokens a ser processado");
    
}else{
try {        
//lex.processa(); //processamento dos lexemas 

contErroSintax = 0;
System.out.println("<<<<<<<<<< INICIANDO ANALISE SINTÃ�TICA >>>>>>>>>>");
jTextArea2.setText("<<<<<<<<<< INICIANDO ANALISE SINTÃ�TICA >>>>>>>>>>"+"\u005cn");
lex.PROGRAMA();

}
catch (Error e)
    
{
System.out.println(e.getMessage());//Mensagem de erro lÃ©xico (em ingles) mostrando linha e coluna
}
finally {/*
if(parser.contParseError > 0 || scanner_1TokenManager.countLexError > 0){
    
    if(parser.contParseError > 0){
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    System.out.println(parser.contParseError +" Erro(s) sintÃ¡tico encontrado.");
    
    }
    if(scanner_1TokenManager.countLexError > 0){
        System.out.println(scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    
    }
    MenssagemTxt.setText("Analize contÃ©m "+parser.contParseError+ " Erro(s) SintÃ¡tico"+ " e "+ scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico");
    MenssagemTxt.setBackground(Color.red);
    MenssagemTxt.setForeground(Color.WHITE);
    
}else{
    //jTextArea2.setText(jTextArea2.getText()+"\u005cn"+"<<<<<<<<<< FINALIZADO COM SUCESSO. >>>>>>>>>>"+"\u005cn"+"\u005cn");
    //MenssagemTxt.setText("Analize sem erro sintÃ¡tico");
    //MenssagemTxt.setBackground(Color.GREEN);
    
}
*/
}
}

}
    public int contErroSintax = 0;
    Scanner_1TokenManager scanner_1TokenManager; 
     private void AnaliseLexSomente() throws IOException{
                
                        EnderecoTemporario =  System.getProperty("java.io.tmpdir")+"temp.txt";
                 File arquivo = new File(EnderecoTemporario);  
                 FileWriter fw = new FileWriter(arquivo);  
                 BufferedWriter bw = new BufferedWriter(fw);      
                 bw.write(jTextArea1.getText());  
                 bw.flush();  
                 bw.close(); 
                 
      
                 
                 String nomeArq = new String (EnderecoTemporario);
Scanner_1 lex = new Scanner_1(new FileInputStream(nomeArq));
String args[] = null;

if(jTextArea1.getText().equals("")){
    JOptionPane.showMessageDialog(null, "NÃ£o ha tokens a ser processado");
    
}else{
try {
         System.out.println("<<<<<<<<<< INICIANDO ANALISE LÃ‰XICA >>>>>>>>>>");
    jTextArea2.setText("<<<<<<<<<< INICIANDO ANALISE LÃ‰XICA >>>>>>>>>>"+"\u005cn"); 
lex.processa(); //processamento dos lexemas 

}

catch (Exception e)
{
JOptionPane.showMessageDialog(null, "Analise Sintaxica NOT OK");
System.out.println("Erro de Token.");

e.printStackTrace();
}
catch (Error e)
{
System.out.println(e.getMessage());//Mensagem de erro lÃ©xico (em ingles) mostrando linha e coluna
}
finally {
    if(scanner_1TokenManager.countLexError > 0){
        jTextArea2.setText(jTextArea2.getText()+"\u005cn"+"\u005cn"+scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico encontrado.");
    MenssagemTxt.setText("Analize contÃ©m "+ scanner_1TokenManager.countLexError +" Erro(s) LÃ©xico");
    MenssagemTxt.setBackground(Color.red);
    MenssagemTxt.setForeground(Color.WHITE);
    
}else{
    jTextArea2.setText(jTextArea2.getText()+"\u005cn"+"\u005cn"+"<<<<<<<<<< FINALIZADO COM SUCESSO. >>>>>>>>>>"+"\u005cn"+"\u005cn");
    MenssagemTxt.setText("Analize sem erro LÃ©xico");
    MenssagemTxt.setBackground(Color.GREEN);
        
    }   
}
}
     }
     
     private class ClockTask extends TimerTask {  
        @Override  
        public void run() {  
            // Aqui chamamos o setHora atravÃ©s da EventQueue da AWT.  
            // Conforme dito, isso garante Thread safety para o Swing.  
            EventQueue.invokeLater(() -> {
                // SÃ³ podemos chamar setHora diretamente dessa
                // forma, pois esse Runnable Ã© uma InnerClass nÃ£o
                // estÃ¡tica.
                MostrarAtualizarDataHora();  
            });  
        }  
    }  
    
    private void MostrarAtualizarDataHora() {
        Locale locale = new Locale("pt","BR");
        GregorianCalendar calendar = new GregorianCalendar();
        SimpleDateFormat formatador = new SimpleDateFormat("'Manaus, 'dd' de 'MMMMM' de 'yyyy' - 'HH':'mm':'ss",locale);
        SimpleDateFormat format = new SimpleDateFormat("ss",locale);
        //System.out.println("Agora: "+(format.format(calendar.getTime())));
        int h = Integer.parseInt(format.format(calendar.getTime()));
        if(h == 1){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im1.jpg")));
        }else if (h == 2  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im2.jpg")));
        
        }else if (h == 3  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im3.jpg")));
        
        }else if (h == 4  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im4.jpg")));
        
        }else if (h == 5  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im5.jpg")));
        
        }else if (h == 6  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im6.jpg")));
        
        }else if (h == 7  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im7.jpg")));
        
        }else if (h == 8  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im8.jpg")));
        
        }else if (h == 9  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im9.jpg")));
        
        }else if (h == 10  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im10.jpg")));
        
        }else if (h ==11  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im1.jpg")));
        
        }else if (h == 12  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im2.jpg")));
        
        }else if (h == 13  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im3.jpg")));
        
        }else if (h == 14  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im4.jpg")));
        
        }else if (h == 15  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im5.jpg")));
            
        }else if (h == 16  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im6.jpg")));
        
        }else if (h == 17  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im7.jpg")));
        
        }else if (h == 18  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im8.jpg")));
        
        }else if (h == 19  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im9.jpg")));
        
        }else if (h == 20  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im10.jpg")));
        
        }else if (h == 21  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im1.jpg")));
        
        }else if (h == 22  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im2.jpg")));
        
        }else if (h == 23  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im3.jpg")));
        
        }else if (h == 24  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im4.jpg")));
        
        }else if (h == 25  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im5.jpg")));
        
        }else if (h == 26  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im6.jpg")));
        
        }else if (h == 27  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im7.jpg")));
        
        }else if (h == 28  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im8.jpg")));
        
        }else if (h == 29  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im9.jpg")));
        
        }else if (h == 30  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im10.jpg")));
        
        }else if (h == 31  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im1.jpg")));
        
        }else if (h == 32  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im2.jpg")));
        
        }else if (h == 33  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im3.jpg")));
        
        }else if (h == 34  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im4.jpg")));
        
        }else if (h == 35  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im5.jpg")));
        
        }else if (h == 36  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im6.jpg")));
        
        }else if (h == 37  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im7.jpg")));
        
        }else if (h == 38  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im8.jpg")));
        
        }else if (h == 39  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im9.jpg")));
        
        }else if (h == 40  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im10.jpg")));
        
        }else if (h == 41  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im1.jpg")));
        
        }else if (h == 42  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im2.jpg")));
        
        }else if (h == 43  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im3.jpg")));
        
        }else if (h == 44  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im4.jpg")));
        
        }else if (h == 45  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im5.jpg")));
        
        }else if (h == 46  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im6.jpg")));
        
        }else if (h == 47  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im7.jpg")));
        
        }else if (h == 48  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im8.jpg")));
        
        }else if (h == 49  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im9.jpg")));
        
        }else if (h == 50  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im10.jpg")));
        
        }else if (h == 51  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im1.jpg")));
        
        }else if (h == 52  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im2.jpg")));
        
        }else if (h == 53  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im3.jpg")));
        
        }else if (h == 54  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im4.jpg")));
        
        }else if (h == 55  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im5.jpg")));
        
        }else if (h == 56  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im6.jpg")));
        
        }else if (h == 57 ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im7.jpg")));
        
        }else if (h == 58  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im8.jpg")));
        
        }else if (h == 59  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im9.jpg")));
        
        }else if (h == 60  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im10.jpg")));
        
        }else if (h == 0  ){
            botao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/im11.jpg")));
        
        }
        //botao1.setText("" + (formatador.format(calendar.getTime())));
        
    }

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Botao_Abrir_Arquivo;
    private javax.swing.JToggleButton Botao_Analizar_lexico;
    private javax.swing.JToggleButton Botao_analizar_sintax;
    private java.awt.Label MenssagemTxt;
    private javax.swing.JButton botao1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
